name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Analysing the code with mypy, black, isort and flake8
      run: |
        poetry run mypy --strict better_weather tests
        poetry run black --check .
        poetry run isort --check better_weather tests
        poetry run flake8 --ignore=W503,E501 better_weather tests
